- type: latheRecipePack
  id: SecurityAmmoStaticOmu
  recipes:
  - MagazineShotgunLeverRifleEmpty
  - MagazineShotgunLeverRifle
  - MagazineBoxPistolRubber
  - MagazinePistolSubMachineGunRubber
  - MagazineBoxCaselessRiflePractice
  - MagazineCaselessRiflePractice
  - MagazineCaselessRifleShortPractice
  - MagazineBoxCaselessRifleFMJ
  - MagazineCaselessRifleFMJ
  - MagazineCaselessRifleShortFMJ
  - MagazineMagnumLeverRifle
  - MagazineMagnumLeverRifleEmpty
  - MagazineClipM1Garand
  - MagazineClipM1GarandEmpty

- type: latheRecipePack
  id: SecurityAmmoOmu
  recipes:
  - MagazineBoxCaselessRifleIncendiary
  - MagazineBoxCaselessRifleUranium
  - MagazineCaselessRifleIncendiary
  - MagazineCaselessRifleUranium
